import_path: SequentialExecutor
init_kwargs:
  reader:
    import_path: HfDatasetReader
    init_kwargs:
      debug: true
      dataset_kwargs:
        path: json
        data_files:
          - data/tmmlu_subquery.jsonl
  writer:
    import_path: HfWriter
    init_kwargs:
      output_path: result/test
  pipes:
    - import_path: AsyncOpenAIChat
      init_kwargs:
        model: gpt-4o-mini
        gen_kwargs:
          top_p: 0.4
          max_tokens: 100
          temperature: 0.8
        user_template: |
          {{ query }}
        output_col: resp
    - import_path: RemoveColumns